### ISSUE TITLE
[Question] How to write fixed length variables separated by ";"?

### ISSUE THREAD

**Issue by rekosko** [leandromoh/RecordParser#67]
Hello,

First of all thanks for great and fast library! :) I have a small problem though. I need to write a file where each line is fixed length e.g.: 1399. When writing a line I need to make sure that each property written is separated by ";" delimiter. Those properties that are written needs to be exactly X characters long so in the end I need to somehow combine two writers?... I'm not really sure whether I can achieve that with your library.

Thanks for any help!

**Comment by leandromoh** [comment]
Hi @rekosko! 

> First of all thanks for great and fast library! :)

Thank you for using it! and glad to know that it is helping to solve people real problems! it was the reason since the beginning

>  I need to write a file where each line is fixed length e.g.: 1399. When writing a line I need to make sure that each property written is separated by ";" delimiter. Those properties that are written needs to be exactly X characters long so in the end I need to somehow combine two writers?... I'm not really sure whether I can achieve that with your library.

I am not sure if I understood your scenario correctly... if you have a fixed length limit for each line (e.g. 1399) I suppose you need to delimited the positions of each field for does not overflow the line limit, right? if yes a simple solution would be to configure a regular fixed length builder and let a single char position unmapped between the fields positions, so you would have some fixed positions you can set with ";" while still having the advantages of use  fixed length builder. something like

```c#
using System;
using RecordParser.Builders.Writer;
using System.Linq;

// note there is an unmapped position of 1 char between the fields 
var writer = new FixedLengthWriterBuilder<(decimal Balance, DateTime Date, decimal Debit)>()
	.Map(x => x.Balance, 0, 12, padding: Padding.Left, paddingChar: '0')
	.Map(x => x.Date, 13, 8)
	.Map(x => x.Debit, 22, 6, padding: Padding.Left, paddingChar: '0')
	.DefaultTypeConvert<decimal>((span, value) => (((long)(value * 100)).TryFormat(span, out var written), written))
	.DefaultTypeConvert<DateTime>((span, value) => (value.TryFormat(span, out var written, "ddMMyyyy"), written))
	.Build();

var instances = new []
{
	(Balance: 123456789.01M, Date: new DateTime(2020, 05, 23), Debit: 0123.45M),
	(Balance: 9876542.01M, Date: new DateTime(2020, 05, 23), Debit: 7653.98M),
	(Balance: 123123.01M, Date: new DateTime(2020, 05, 23), Debit: 555.23M),
};

Span<char> destination = Enumerable.Repeat(';', 50).ToArray();
foreach(var instance in instances)
{
	writer.TryFormat(instance, destination, out var charsWritten);
	Console.WriteLine(destination.Slice(0, charsWritten).ToString());
}
```
would print the following:
```
012345678901;23052020;012345
000987654201;23052020;765398
000012312301;23052020;055523
```
does it help you? 
the original idea came from [this unit test](https://github.com/leandromoh/RecordParser/blob/master/RecordParser.Test/FixedLengthWriterBuilderTest.cs#L157).
I used [this dotnetfiddle to test](https://dotnetfiddle.net/NXWFBo).
if the problem already have been solved, please share with us your solution

Sorry for the late reply.

**Comment by rekosko** [comment]
Hi,

Thanks for providing help but in the end I needed to do much more but I was able to solve my issue with custom `.Map()` method.

I had to write properties separated by `;` but in the same time wrapped with `"` - crazy, I know :)

```
 _writer = new VariableLengthWriterSequentialBuilder<CSTRCKPARAM>().Map(x => x.ExampleProperty1, 3)
                .Map(x => x.ExampleProperty2, 6)
                .Build(";");
```

```
public static IVariableLengthWriterSequentialBuilder<T> Map<T>(this IVariableLengthWriterSequentialBuilder<T> builder,
            Expression<Func<T, string>> ex,
            int? length,
            char? wrappingChar = '"')
        {
            builder.Map(ex, (span, value) => (value.TryFormat(span, out var written, length, wrappingChar: wrappingChar), written));
            return builder;
        }

        public static bool TryFormat(this string value,
            Span<char> destination,
            out int charsWritten,
            int? length,
            Padding padding = Padding.Right,
            char paddingChar = ' ',
            char? wrappingChar = null)
        {
            if (value.Length > destination.Length)
            {
                charsWritten = 0;
                return false;
            }

            if (length is > 0)
            {
                value = padding switch
                {
                    Padding.Right => value.PadRight(length.Value, paddingChar),
                    Padding.Left => value.PadLeft(length.Value, paddingChar),
                    _ => value
                };
            }

            if (wrappingChar is not null)
            {
                value = $"{wrappingChar}{value}{wrappingChar}";
            }

            if (value.TryCopyTo(destination))
            {
                charsWritten = destination.Length;
                return true;
            }

            charsWritten = 0;
            return false;
        }
```
        
This gives me:

```
"000095";"TEST1                                   ";"000427245";"XXX Y AAA                               ";"000427245";"00003040098";"91900657301";"26";"
````
