### ISSUE TITLE
[Question] Did you tried using Source Generator?

### ISSUE THREAD

**Issue by AlbertoMonteiro** [leandromoh/RecordParser#95]
Is just a question, have you tried using Source Generator.

I know that there are limitations related to C# version(min 9), but I just wanted to know if you even tried it.

**Comment by leandromoh** [comment]
Hi @AlbertoMonteiro !

This is something I have considered, but never tried. It would be very insteresting use source generators, specially in AOT scenario.
Recently I created the following related issue: https://github.com/agileobjects/ReadableExpressions/issues/135

**Comment by leandromoh** [comment]
I am going to close the issue, ok ? If necessary we can reopen it.
